# when:
#   # - event: [pull_request, tag, cron]
#   - event: push
#     branch:
#       - ${CI_REPO_DEFAULT_BRANCH}
#       - 'draft/*'

steps:
  - name: publish
    image: python:3.11-alpine
    commands:
      - apk add curl
      - curl -sSL https://pdm-project.org/install-pdm.py | python3 -
      - export PATH="/root/.local/bin:$PATH"
      - pdm install
      - pdm run invoke cname preview
