steps:
  - name: publish
    image: 3.11-alpine
    commands:
      - curl -sSL https://pdm-project.org/install-pdm.py | python3 -
      - pdm install
      - make publish
    when:
      - branch: main
